// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alerts.sql

package db

import (
	"context"
)

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (monitor_id, type, destination)
VALUES ($1, $2, $3)
RETURNING id, monitor_id, type, destination, created_at
`

type CreateAlertParams struct {
	MonitorID   int64  `json:"monitor_id"`
	Type        string `json:"type"`
	Destination string `json:"destination"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, createAlert, arg.MonitorID, arg.Type, arg.Destination)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.Type,
		&i.Destination,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAlert = `-- name: DeleteAlert :exec
DELETE FROM alerts
WHERE id = $1 AND monitor_id = $2
`

type DeleteAlertParams struct {
	ID        int64 `json:"id"`
	MonitorID int64 `json:"monitor_id"`
}

func (q *Queries) DeleteAlert(ctx context.Context, arg DeleteAlertParams) error {
	_, err := q.db.Exec(ctx, deleteAlert, arg.ID, arg.MonitorID)
	return err
}

const listAlertsByMonitor = `-- name: ListAlertsByMonitor :many
SELECT id, monitor_id, type, destination, created_at FROM alerts
WHERE monitor_id = $1
`

func (q *Queries) ListAlertsByMonitor(ctx context.Context, monitorID int64) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsByMonitor, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Alert
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.Type,
			&i.Destination,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
