// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: incidents.sql

package db

import (
	"context"
)

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (monitor_id)
VALUES ($1)
RETURNING id, monitor_id, started_at, resolved_at, notified
`

func (q *Queries) CreateIncident(ctx context.Context, monitorID int64) (Incident, error) {
	row := q.db.QueryRow(ctx, createIncident, monitorID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.Notified,
	)
	return i, err
}

const getActiveIncident = `-- name: GetActiveIncident :one
SELECT id, monitor_id, started_at, resolved_at, notified FROM incidents
WHERE monitor_id = $1
AND resolved_at IS NULL
LIMIT 1
`

func (q *Queries) GetActiveIncident(ctx context.Context, monitorID int64) (Incident, error) {
	row := q.db.QueryRow(ctx, getActiveIncident, monitorID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.Notified,
	)
	return i, err
}

const listIncidentsByMonitor = `-- name: ListIncidentsByMonitor :many
SELECT id, monitor_id, started_at, resolved_at, notified FROM incidents
WHERE monitor_id = $1
ORDER BY started_at DESC
`

func (q *Queries) ListIncidentsByMonitor(ctx context.Context, monitorID int64) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidentsByMonitor, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.Notified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markIncidentNotified = `-- name: MarkIncidentNotified :exec
UPDATE incidents
SET notified = true
WHERE monitor_id = $1
AND resolved_at IS NULL
`

func (q *Queries) MarkIncidentNotified(ctx context.Context, monitorID int64) error {
	_, err := q.db.Exec(ctx, markIncidentNotified, monitorID)
	return err
}

const resolveIncident = `-- name: ResolveIncident :one
UPDATE incidents
SET resolved_at = now()
WHERE monitor_id = $1
AND resolved_at IS NULL
RETURNING id, monitor_id, started_at, resolved_at, notified
`

func (q *Queries) ResolveIncident(ctx context.Context, monitorID int64) (Incident, error) {
	row := q.db.QueryRow(ctx, resolveIncident, monitorID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.Notified,
	)
	return i, err
}
