// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID          int64              `json:"id"`
	MonitorID   int64              `json:"monitor_id"`
	Type        string             `json:"type"`
	Destination string             `json:"destination"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CheckResult struct {
	ID         int64              `json:"id"`
	MonitorID  int64              `json:"monitor_id"`
	Status     string             `json:"status"`
	LatencyMs  int32              `json:"latency_ms"`
	StatusCode pgtype.Int4        `json:"status_code"`
	CheckedAt  pgtype.Timestamptz `json:"checked_at"`
}

type Incident struct {
	ID         int64              `json:"id"`
	MonitorID  int64              `json:"monitor_id"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	Notified   bool               `json:"notified"`
}

type Monitor struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	Name         string             `json:"name"`
	Url          string             `json:"url"`
	IntervalSecs int32              `json:"interval_secs"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        int64              `json:"id"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
