// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO monitors (user_id, name, url, interval_secs)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, url, interval_secs, is_active, created_at
`

type CreateMonitorParams struct {
	UserID       int64  `json:"user_id"`
	Name         string `json:"name"`
	Url          string `json:"url"`
	IntervalSecs int32  `json:"interval_secs"`
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, createMonitor,
		arg.UserID,
		arg.Name,
		arg.Url,
		arg.IntervalSecs,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.IntervalSecs,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMonitor = `-- name: DeleteMonitor :exec
UPDATE monitors
SET is_active = false
WHERE id = $1 AND user_id = $2
`

type DeleteMonitorParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteMonitor(ctx context.Context, arg DeleteMonitorParams) error {
	_, err := q.db.Exec(ctx, deleteMonitor, arg.ID, arg.UserID)
	return err
}

const getMonitorByID = `-- name: GetMonitorByID :one
SELECT id, user_id, name, url, interval_secs, is_active, created_at FROM monitors
WHERE id = $1
`

func (q *Queries) GetMonitorByID(ctx context.Context, id int64) (Monitor, error) {
	row := q.db.QueryRow(ctx, getMonitorByID, id)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.IntervalSecs,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getMonitorStats = `-- name: GetMonitorStats :one
SELECT
  COUNT(*) AS total_monitors,
  COUNT(*) FILTER (WHERE is_active = true) AS healthy_monitors
FROM monitors
WHERE user_id = $1
`

type GetMonitorStatsRow struct {
	TotalMonitors   int64 `json:"total_monitors"`
	HealthyMonitors int64 `json:"healthy_monitors"`
}

func (q *Queries) GetMonitorStats(ctx context.Context, userID int64) (GetMonitorStatsRow, error) {
	row := q.db.QueryRow(ctx, getMonitorStats, userID)
	var i GetMonitorStatsRow
	err := row.Scan(&i.TotalMonitors, &i.HealthyMonitors)
	return i, err
}

const getMonitorWithStats = `-- name: GetMonitorWithStats :one
SELECT
  m.id,
  m.user_id,
  m.name,
  m.url,
  m.interval_secs,
  m.is_active,
  m.created_at,
  COALESCE(latest.status, 'unknown') AS current_status,
  COALESCE(stats.uptime_percentage, 0) AS uptime_percentage,
  COALESCE(stats.avg_latency_ms, 0)::INT AS avg_latency_ms,
  latest.checked_at AS last_checked_at,
  latest.status AS last_check_status
FROM monitors m
LEFT JOIN LATERAL (
  SELECT status, checked_at
  FROM check_results
  WHERE monitor_id = m.id
  ORDER BY checked_at DESC
  LIMIT 1
) latest ON true
LEFT JOIN LATERAL (
  SELECT
    COUNT(*) FILTER (WHERE status = 'up') * 100 / NULLIF(COUNT(*), 0) AS uptime_percentage,
    AVG(latency_ms) AS avg_latency_ms
  FROM check_results
  WHERE monitor_id = m.id
  AND checked_at > now() - INTERVAL '24 hours'
) stats ON true
WHERE m.id = $1 AND m.is_active = true
`

type GetMonitorWithStatsRow struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	Name             string             `json:"name"`
	Url              string             `json:"url"`
	IntervalSecs     int32              `json:"interval_secs"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CurrentStatus    string             `json:"current_status"`
	UptimePercentage int32              `json:"uptime_percentage"`
	AvgLatencyMs     int32              `json:"avg_latency_ms"`
	LastCheckedAt    pgtype.Timestamptz `json:"last_checked_at"`
	LastCheckStatus  string             `json:"last_check_status"`
}

func (q *Queries) GetMonitorWithStats(ctx context.Context, id int64) (GetMonitorWithStatsRow, error) {
	row := q.db.QueryRow(ctx, getMonitorWithStats, id)
	var i GetMonitorWithStatsRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.IntervalSecs,
		&i.IsActive,
		&i.CreatedAt,
		&i.CurrentStatus,
		&i.UptimePercentage,
		&i.AvgLatencyMs,
		&i.LastCheckedAt,
		&i.LastCheckStatus,
	)
	return i, err
}

const listAllActiveMonitors = `-- name: ListAllActiveMonitors :many
SELECT id, user_id, name, url, interval_secs, is_active, created_at FROM monitors
WHERE is_active = true
`

func (q *Queries) ListAllActiveMonitors(ctx context.Context) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listAllActiveMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Url,
			&i.IntervalSecs,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitorsByUser = `-- name: ListMonitorsByUser :many
SELECT id, user_id, name, url, interval_secs, is_active, created_at FROM monitors
WHERE user_id = $1 AND is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListMonitorsByUser(ctx context.Context, userID int64) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listMonitorsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Url,
			&i.IntervalSecs,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitorsWithStats = `-- name: ListMonitorsWithStats :many
SELECT
  m.id,
  m.user_id,
  m.name,
  m.url,
  m.interval_secs,
  m.is_active,
  m.created_at,
  COALESCE(latest.status, 'unknown') AS current_status,
  COALESCE(stats.uptime_percentage, 0) AS uptime_percentage,
  COALESCE(stats.avg_latency_ms, 0)::INT AS avg_latency_ms,
  latest.checked_at AS last_checked_at,
  latest.status AS last_check_status
FROM monitors m
LEFT JOIN LATERAL (
  SELECT status, checked_at
  FROM check_results
  WHERE monitor_id = m.id
  ORDER BY checked_at DESC
  LIMIT 1
) latest ON true
LEFT JOIN LATERAL (
  SELECT
    COUNT(*) FILTER (WHERE status = 'up') * 100 / NULLIF(COUNT(*), 0) AS uptime_percentage,
    AVG(latency_ms) AS avg_latency_ms
  FROM check_results
  WHERE monitor_id = m.id
  AND checked_at > now() - INTERVAL '24 hours'
) stats ON true
WHERE m.user_id = $1 AND m.is_active = true
ORDER BY m.created_at DESC
`

type ListMonitorsWithStatsRow struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	Name             string             `json:"name"`
	Url              string             `json:"url"`
	IntervalSecs     int32              `json:"interval_secs"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	CurrentStatus    string             `json:"current_status"`
	UptimePercentage int32              `json:"uptime_percentage"`
	AvgLatencyMs     int32              `json:"avg_latency_ms"`
	LastCheckedAt    pgtype.Timestamptz `json:"last_checked_at"`
	LastCheckStatus  string             `json:"last_check_status"`
}

func (q *Queries) ListMonitorsWithStats(ctx context.Context, userID int64) ([]ListMonitorsWithStatsRow, error) {
	rows, err := q.db.Query(ctx, listMonitorsWithStats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMonitorsWithStatsRow
	for rows.Next() {
		var i ListMonitorsWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Url,
			&i.IntervalSecs,
			&i.IsActive,
			&i.CreatedAt,
			&i.CurrentStatus,
			&i.UptimePercentage,
			&i.AvgLatencyMs,
			&i.LastCheckedAt,
			&i.LastCheckStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMonitor = `-- name: UpdateMonitor :one
UPDATE monitors
SET name = $2, url = $3, interval_secs = $4
WHERE id = $1 AND user_id = $5
RETURNING id, user_id, name, url, interval_secs, is_active, created_at
`

type UpdateMonitorParams struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	Url          string `json:"url"`
	IntervalSecs int32  `json:"interval_secs"`
	UserID       int64  `json:"user_id"`
}

func (q *Queries) UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, updateMonitor,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.IntervalSecs,
		arg.UserID,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.IntervalSecs,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
