// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitors.sql

package db

import (
	"context"
)

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO monitors (user_id, name, url, interval_secs)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, url, interval_secs, is_active, created_at
`

type CreateMonitorParams struct {
	UserID       int64  `json:"user_id"`
	Name         string `json:"name"`
	Url          string `json:"url"`
	IntervalSecs int32  `json:"interval_secs"`
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, createMonitor,
		arg.UserID,
		arg.Name,
		arg.Url,
		arg.IntervalSecs,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.IntervalSecs,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMonitor = `-- name: DeleteMonitor :exec
UPDATE monitors
SET is_active = false
WHERE id = $1 AND user_id = $2
`

type DeleteMonitorParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteMonitor(ctx context.Context, arg DeleteMonitorParams) error {
	_, err := q.db.Exec(ctx, deleteMonitor, arg.ID, arg.UserID)
	return err
}

const getMonitorByID = `-- name: GetMonitorByID :one
SELECT id, user_id, name, url, interval_secs, is_active, created_at FROM monitors
WHERE id = $1
`

func (q *Queries) GetMonitorByID(ctx context.Context, id int64) (Monitor, error) {
	row := q.db.QueryRow(ctx, getMonitorByID, id)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.IntervalSecs,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getMonitorStats = `-- name: GetMonitorStats :one
SELECT
  COUNT(*) AS total_monitors,
  COUNT(*) FILTER (WHERE is_active = true) AS active_monitors
FROM monitors
WHERE user_id = $1
`

type GetMonitorStatsRow struct {
	TotalMonitors  int64 `json:"total_monitors"`
	ActiveMonitors int64 `json:"active_monitors"`
}

func (q *Queries) GetMonitorStats(ctx context.Context, userID int64) (GetMonitorStatsRow, error) {
	row := q.db.QueryRow(ctx, getMonitorStats, userID)
	var i GetMonitorStatsRow
	err := row.Scan(&i.TotalMonitors, &i.ActiveMonitors)
	return i, err
}

const listAllActiveMonitors = `-- name: ListAllActiveMonitors :many
SELECT id, user_id, name, url, interval_secs, is_active, created_at FROM monitors
WHERE is_active = true
`

func (q *Queries) ListAllActiveMonitors(ctx context.Context) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listAllActiveMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Url,
			&i.IntervalSecs,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitorsByUser = `-- name: ListMonitorsByUser :many
SELECT id, user_id, name, url, interval_secs, is_active, created_at FROM monitors
WHERE user_id = $1 AND is_active = true
ORDER BY created_at DESC
`

func (q *Queries) ListMonitorsByUser(ctx context.Context, userID int64) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listMonitorsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Url,
			&i.IntervalSecs,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMonitor = `-- name: UpdateMonitor :one
UPDATE monitors
SET name = $2, url = $3, interval_secs = $4
WHERE id = $1 AND user_id = $5
RETURNING id, user_id, name, url, interval_secs, is_active, created_at
`

type UpdateMonitorParams struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	Url          string `json:"url"`
	IntervalSecs int32  `json:"interval_secs"`
	UserID       int64  `json:"user_id"`
}

func (q *Queries) UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, updateMonitor,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.IntervalSecs,
		arg.UserID,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Url,
		&i.IntervalSecs,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
