// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error)
	CreateCheckResult(ctx context.Context, arg CreateCheckResultParams) (CheckResult, error)
	CreateIncident(ctx context.Context, monitorID int64) (Incident, error)
	CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAlert(ctx context.Context, arg DeleteAlertParams) error
	DeleteMonitor(ctx context.Context, arg DeleteMonitorParams) error
	GetActiveIncident(ctx context.Context, monitorID int64) (Incident, error)
	GetMonitorByID(ctx context.Context, id int64) (Monitor, error)
	GetUptimePercentage(ctx context.Context, monitorID int64) (int32, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListAlertsByMonitor(ctx context.Context, monitorID int64) ([]Alert, error)
	ListAllActiveMonitors(ctx context.Context) ([]Monitor, error)
	ListCheckResultsByMonitor(ctx context.Context, monitorID int64) ([]CheckResult, error)
	ListIncidentsByMonitor(ctx context.Context, monitorID int64) ([]Incident, error)
	ListMonitorsByUser(ctx context.Context, userID int64) ([]Monitor, error)
	ResolveIncident(ctx context.Context, monitorID int64) (Incident, error)
	UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (Monitor, error)
}

var _ Querier = (*Queries)(nil)
